---
title: "Information about the dataset used for demonstrations"
---
<div style="line-height: 1.7em;">

* Dataset of 20 individuals with 9 self-report variables (and time of response) each, used for testing data generating processes [here](https://raw.githubusercontent.com/heinonmatti/complexity-behchange/master/data/data_20p_9var_plus_time.csv).
* Dataset of one of these participants used in examples of the manuscript [here](https://raw.githubusercontent.com/heinonmatti/complexity-behchange/master/data/EMA_data_Moti_P10.csv).

The dataset contains of 20 individuals, each of whom used a mobile application to collect motivation data. 19 of these took part in an observational ecological momentary assessment (EMA) study to inspect fluctuations of work motivation. One individual, user Moti_P17, is an author of the manuscript (Matti Heino), who wanted to collect a long-enough time series to allow for fractal analyses, which is why this person's dataset is exceedingly long. All individuals were beeped five times during an 8-hour window, starting from a time they set themselves to be their normal work start time. The 19 motivation study participants were instructed to collect as many time points as they wished, with 150 observations allowing for in-depth modeling of their data.    

All questions were forced input, hence there is no missing data from those occasions where a response has been made. But in order to collect enough time points, the participants were instructed such, that if they are not able to respond when the beep takes place, they can return to the mobile app whenever is a good time to them. Accordingly, number of answers during a day varies widely, as well as their temporal distance within a day. There are also gaps in many participant's data, due to weekends and (e.g. Christmas) holidays.

For each person, the dataset only contains those 9 variables, which relate to perceived reasons for doing the task at hand, that is, self-determination theory based motivation\*, as well as perceived basic needs satisfaction\*\*. Each of these items was shown on a Visual Analog Scale (VAS) which was implicitly mapped to a value between 0 and 49.

\* I am working on this task because... _It is pleasurable_ (intrinsic); _it is interesting_ (intrinsic); _it is important to me_ (identified); _someone else wants me to_ (external); _the situation requires me to_ (external); _I would feel guilty or anxious if I did not_ (introjected). Items were adapted from Ketonen et al., 2018 (DOI: 10.1016/j.learninstruc.2017.07.003).

\*\* _I feel competent in what I'm doing_ (competence), _I feel free to choose the best way of working_ (autonomy), _I feel a sense of belonging to my colleagues_ (relatedness). Items were picked, and adapted to reflect momentary assessment, from Broeck et al., 2010 (DOI: 10.1348/096317909X481382)

The omitted items inquired time since last break, self-motivational strategies used, and an optional personal VAS-question the participants would track. In addition, the first questionnaire of the day also contained a question about previous night’s sleep quality (VAS, rated from worst possible to best possible), and the end of day questionnaire contained items on job satisfaction (VAS, rated from very dissatisfied to very satisfied) and job performance (VAS, rated from worst quality to best quality). These are not included in this dataset but will be released along with another manuscript, which focuses on the work motivation EMA study. These items are included in the processed dataset of participant Moti_P10.

After installing package readr, the dataset with 20 individuals can be read to R with:

`mydata <- readr::read_csv("./my_path_name/data_20p_9var_plus_time.csv")`

The dataset with one individual can be read to R with:

`emadata <- readr::read_csv("./my_path_name/EMA_data_Moti_P10.csv")`

</div>